#!/bin/bash

#####exmaple of Calling this file, just add this part at the end of ~/.bashrc
#if [ -f ~/data/_mybashrc ]; then
#    . ~/data/_mybashrc
#fi
#--------------------------------------------------

echo "Calling _mybashrc file setting"
alias ls='ls --color=auto'
alias grep='grep --color=auto'




alias la='ls -alh'

###############alias for tags generation
#alias ctags='the_ctags_in_your_env'
alias ctags_R='ctags -R --c++-kinds=+px --fields=+iaS --extra=+qf'
alias ctags_R_Python="ctags -R --python-kinds=+vi --fields=+iaSKz --extra=+qf"
alias ctags_R_SV="ctags -R --systemverilog-kinds=+ctfeilmpdva --fields=+iaSKz --extra=+qf"

#sudo apt install openjdk-8-jdk
export BrissInstallPath='~/data/tools/briss/briss-0.9'
alias OpenBriss="java -jar ${BrissInstallPath}/briss-0.9.jar"
