#!/usr/bash


sudo apt update

#if [ -f ~/_mybashrc ]; then
#    . ~/_mybashrc
#fi
sudo apt install dpkg

wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

sudo dpkg -i google-chrome-stable_current_amd64.deb
