#!/usr/bash
sudo add-apt-repository ppa:jonathonf/vim
sudo add-apt-repository ppa:jonathonf/python-3.6
sudo add-apt-repository ppa:jonathonf/python-2.7
sudo add-apt-repository ppa:jonathonf/gcc


sudo apt update
sudo apt install vim gcc python python-dev clang clang-4.0 python-dev python3-dev
sudo apt install git
sudo apt-get -f install
sudo apt install vim git
sudo apt-get install build-essential cmake llvm-4.0 libclang-4.0-dev libboost-all-dev
#get bundle plugin tools if internet is available
mkdir -p ~/.vim/bundle/
cd ~/.vim/bundle/
git clone --recursive https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
#git clone https://github.com/gmarik/Vundle.vim.git  ~/.vim/bundle/Vundle.vim
#gvim
#vim
vim +PluginInstall +qall
#:PluginInstall
cd ~/.vim/bundle/YouCompleteMe
./install.py --clang-completer
#"or
#"./install.py --all
#" will download clang and other pludgin automatically
vim
