#!/bin/bash

echo "please note, it is better to run just times"
sudo apt update
sudo apt install emacs

#bash format
#if [ -f ~/_mybashrc ]; then
#    . ~/_mybashrc
#fi

#tcsh format
#if ( -f ~/_mycshrc ) then
#    . ~/_mycshrc
#endif

if [ -f ~/.emacs ]; then
  echo "~/.emacs is there" ;
  echo  '(load "'"`pwd`"'/_emacs")'  >>  ~/.emacs ;
else
  echo "~/.emacs is not there" ;
  echo  '(load "'"`pwd`"'/_emacs")'  >  ~/.emacs ;
fi

if [ -d ~/.emacs.d ]; then
  echo  "There is .emacs.d folder, will back up it" ;
  \mv -f  ~/.emacs.d ~/.emacs.d.back."`date +%Y-%m-%d-%H%M`" ;
else
  echo  "There is no .emacs.d folder in your home" ;
fi
#  \cp -rf ./_emacs.d ~/.emacs.d ;
  \ln -sf  `pwd`/_emacs.d ~/.emacs.d ;

emacs &
