#!/usr/bash


sudo apt update
sudo apt install ctags

#if [ -f ~/_mybashrc ]; then
#    . ~/_mybashrc
#fi

if [ -f ~/.ctags ]; then
  cat "#add `pwd`/_ctags file contents"  >>  ~/.ctags
  cat _ctags >>  ~/.ctags
else
  ln -s `pwd`/_ctags ~/.ctags 
fi
