#!/bin/bash

echo "Please note, it is better to run just for initial env"

#add emacs ppa source
sudo add-apt-repository ppa:kelleyk/emacs

sudo apt update

#install emancs v26 here, you could install new version if you like
sudo apt install emacs26 emacs26-common
#sudo apt install emacs

#bash format
#if [ -f ~/_mybashrc ]; then
#    . ~/_mybashrc
#fi

#tcsh format
#if ( -f ~/_mycshrc ) then
#    . ~/_mycshrc
#endif

#link the _emacs to your home path
if [ -f ~/.emacs ]; then
  echo "~/.emacs is there" ;
  echo  '(load "'"`pwd`"'/_emacs")'  >>  ~/.emacs ;
else
  echo "~/.emacs is not there" ;
  echo  '(load "'"`pwd`"'/_emacs")'  >  ~/.emacs ;
fi

#to get and use redguardtoo stable setup
git clone https://github.com/redguardtoo/emacs.d.git _emacs.d;
cd _emacs.d;
git reset --hard stable

#link the _emacs.d to your home path
if [ -d ~/.emacs.d ]; then
  echo  "There is .emacs.d folder, will back up it" ;
  \mv -f  ~/.emacs.d ~/.emacs.d.back."`date +%Y-%m-%d-%H%M`" ;
else
  echo  "There is no .emacs.d folder in your home" ;
fi
#  \cp -rf ./_emacs.d ~/.emacs.d ;
  \ln -sf  `pwd`/_emacs.d ~/.emacs.d ;

emacs &
