#!/usr/bin/bash

#install
sudo apt-get install samba
sudo apt-get install cifs-utils
#set config of samba server
sudo cp /etc/samba/smb.conf /etc/samba/smb.conf.original
sudo gedit /etc/samba/smb.conf
#create the sharefolder
mkdir -p FolderNameSharedWithPath
#add the following part for one share folder in end of smb.conf. 
#copy multi pcs and udpate the name and path for multi sharing
#--------------------------------------------------
[ShareFolderNameShown]
      path = FolderNameSharedWithPath
      available = yes
      browsealbe = yes
      public = yes
      writable = yes
#--------------------------------------------------
#create the samba user and password
sudo touch /etc/samba/smbpasswd
sudo smbpasswd -a UserNameYouLike
#restart the samba server
sudo /etc/init.d/samba restart
#work now?
